import { MONSTERS, encounter, gradeProgress, monsterById, weakQuestions } from './game.js';
import { icon, monster, landscape } from './art.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function battleScreen(game,questions,animate=false) {
 const b=game.active,practice=b.round.mode==='practice',base=monsterById(b.monsterId),m=practice?{...base,grade:b.round.grade,area:b.round.grade-1}:base,q=b.round.current,f=b.feedback;
 const hit=animate&&f?.correct, intro=animate&&!f&&!b.answers&&m.kind!=='normal'&&!practice;
 const percent=100*b.hp/b.maxHp, before=100*(f?.hpBefore??b.hp)/b.maxHp;
 return `<section class="battle-shell encounter-${m.kind}"><div class="battle-top"><button class="quiet" data-action="pause">${icon('pause')}休けい</button><span>${practice?`復習バトル · ${b.targets.length}問`:`${m.grade}年 · ${m.stage+1}/20`}</span><span class="remaining-count">${b.won?'クリア！':`あと ${b.targets.length-b.solved.length} 問`}</span></div>
 <div class="battle-grid ${m.kind}"><div class="arena ${hit?'hit-motion':''} ${hit&&f.special?'combo-motion':''} ${b.won?'won':''} ${hit&&b.won?'defeat-motion':''}">
 ${landscape(m.area)}<div class="arena-vignette"></div><div class="arena-platform"></div><div class="enemy-status"><div><span class="rank">${!practice&&(m.element==='草'||m.element==='森')?icon('leaf'):''}${practice?'図鑑に残らない特別な竜':m.kind==='final'?'天空の王':m.kind==='boss'?'ボス':m.element+'の竜'}</span><h2>${m.name}</h2></div><span class="hp-numbers"><small>HP </small>${b.hp}<small> / ${b.maxHp}</small></span><div class="hp" style="--before:${before}%;--after:${percent}%" role="progressbar" aria-label="ドラゴンのHP" aria-valuenow="${b.hp}" aria-valuemin="0" aria-valuemax="${b.maxHp}"><i class="hp-ghost" style="width:${percent}%"></i><i style="width:${percent}%"></i></div></div>
 <div class="battle-monster">${monster(m)}</div>
 ${hit?`<div class="attack-slash" aria-hidden="true"></div><div class="hit-ring" aria-hidden="true"></div><div class="hit-sparks" aria-hidden="true">${Array.from({length:8},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="damage" aria-hidden="true"><small>${b.won?'とどめ！':f.special?'れんぞく正解！':''}</small>−${f.damage}</div>`:''}
 ${b.won?`<div class="victory-seal" role="status"><span>${practice?'復習':'討伐'}</span><b>${practice?'クリア！':'成功！'}</b></div>`:''}
 ${intro?`<div class="boss-intro" aria-label="${m.name}登場"><span>${m.kind==='final'?'天空の王、降臨':'ボス出現'}</span><b>${m.name}</b><i></i></div>`:''}
 <div class="battle-power"><span class="combo ${b.combo>=3?'hot':''}">${b.combo>=2?`<b>${b.combo}</b> れんぞく正解`:'正解で攻撃'}</span><span>1問正解 ＝ 10ダメージ</span></div></div>
 <div class="quiz"><div class="quiz-label">${game.profile.records[q.id]?.wrong>0?'<span>もう一度チャレンジ</span>':''}<div class="quiz-progress"><span>${b.solved.length} / ${b.targets.length} 問クリア</span><div class="progress-dots" aria-hidden="true">${b.targets.map((_,i)=>`<span class="progress-dot${i<b.solved.length?' is-complete':''}"></span>`).join('')}</div></div></div><p class="question-instruction" tabindex="-1" data-focus>？に入る漢字は？</p><p class="reading">${esc(q.reading)}</p><h1 class="word" aria-label="${esc(q.reading)}。${[...q.word].map((c,i)=>i===q.blank&&!f?'空欄':c).join('、')}">${[...q.word].map((c,i)=>i===q.blank?`<span class="blank ${f?'solved':''}">${f?esc(c):'？'}</span>`:`<span>${esc(c)}</span>`).join('')}</h1><p class="hint">${esc(q.hint)}</p>
 <div class="answers" role="group" aria-label="答えを選ぶ">${b.round.options.map((c,i)=>`<button class="answer ${f?c===q.answer?'correct':c===f.choice?'incorrect':'dimmed':''}" data-choice="${esc(c)}" aria-label="${esc(c)}" ${f?'disabled':''}><span>${esc(c)}</span><kbd>${i+1}</kbd>${f&&c===q.answer?icon('check'):''}</button>`).join('')}</div>
 <div class="feedback ${f?f.correct?'good':'learn':''}" role="status">${f?`<div><b>${f.correct?b.won?practice?'れんしゅうクリア！':'ドラゴンをたおした！':f.retry?'できた！':'せいかい！':`答えは「${esc(q.word)}」`}</b>${!f.correct?`<span>${esc(q.reading)} · あとで、もう一度やろう。</span>`:''}</div><button class="next-answer" data-action="next">${b.won?practice?'結果を見る':'仲間にする':f.correct?'つぎへ':'おぼえた！'} ${icon('arrow')}</button>`:'<span>あせらず、えらぼう。</span>'}</div>
 ${b.unlocked.length?'<p class="legend-note">全問せいかい！ 天空の王が図鑑に加わった！</p>':''}
 </div></div></section>`;
}
export function rewardScreen(game,questions,animate=false) {
 const b=game.active,practice=b.round.mode==='practice',base=monsterById(b.monsterId),m=practice?{...base,grade:b.round.grade,area:b.round.grade-1}:base,next=encounter(game),p=gradeProgress(game,questions);
 const found=MONSTERS.filter(x=>x.grade===m.grade&&game.catches[x.id]).length, complete=!practice&&found===20&&p.complete;
 return `<section class="reward-shell ${m.kind} ${animate?'reveal-motion':''}"><div class="reward-art"><div class="capture-orbit"></div><div class="capture-rays"></div><span class="reward-ribbon">${practice?'ファントムをしずめた！':b.newCatch?'なかまになった！':'もう一度、勝利！'}</span>${monster(m)}<div class="capture-stars" aria-hidden="true">${Array.from({length:12},(_,i)=>`<i style="--i:${i}">✦</i>`).join('')}</div></div><div class="reward-copy"><p class="eyebrow">${practice?'今日の復習 · 図鑑には載りません':`${m.grade}年の冒険 · ${found}/20体`}</p><h1 tabindex="-1" data-focus>${practice?'よくできました！':m.name}</h1><p class="result-line">${b.correct}問せいかい${b.missed.length?` · ${b.missed.length}問にもう一度挑戦`:' · 全問せいかい！'}</p>
 ${b.unlocked.length?`<div class="legend-unlock">天空の王も、なかまに！${monster(MONSTERS.find(x=>x.id===b.unlocked[0]))}</div>`:''}
 ${complete?`<div class="grade-complete"><b>${m.grade}年生 コンプリート！</b><span>20体のドラゴンと、${p.total}問をクリア！</span></div>`:practice?`<p class="study-summary">${weakQuestions(game,questions).length?'また5問ずつ、練習しよう。':'復習する問題は、ぜんぶクリア！'}</p>`:`<div class="next-discovery"><div class="next-silhouette">${monster(next,{silhouette:!game.catches[next.id]})}</div><div><small>${next.kind==='boss'?'つぎはボス！':next.kind==='final'?'つぎは天空の王！':'つぎの相手'}</small><b>${next.name}</b></div></div>`}
 <button class="primary wide" data-action="${complete||practice?'finish':'again'}">${complete?'ほかの学年をえらぶ':practice?'ホームへ':next.kind==='normal'?'つぎの竜へ':'ボスにいどむ'} ${icon('arrow')}</button><div class="reward-links">${practice?'':`<button class="quiet" data-action="finish">今日はここまで</button>`}<button class="quiet" data-action="reward-book">${icon('book')}図鑑を見る</button></div>
 <p class="reward-progress">${m.grade}年の漢字 <b>${p.mastered} / ${p.total}</b> 問せいかい</p>
 ${b.missed.length?`<details class="review"><summary>もう一度おぼえたい ${b.missed.length} 語</summary>${b.missed.map(id=>questions.find(q=>q.id===id)).filter(Boolean).map(q=>`<p><ruby>${esc(q.word)}<rt>${esc(q.reading)}</rt></ruby><span>${esc(q.hint)}</span></p>`).join('')}<button class="quiet" data-action="history">まちがいノートへ</button></details>`:''}
 ${practice?'':`<details class="dragon-lore"><summary>このドラゴンについて</summary><p>${m.element} · ${'★'.repeat(m.stars)}</p><p>${m.lore}</p></details>`}</div></section>`;
}
