import { AREAS, MONSTERS, monsterById, encounter, gradeProgress, mistakeHistory, weakQuestions, battleTargets } from './game.js';
import { icon, monster, landscape } from './art.js';
const esc = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export function requirement(game, questions, m) {
 return m.kind==='final'?'この学年の全問に1回ずつ正解': 'ステージ '+(m.stage+1)+'で出会える';
}
export function progressPanel(game,questions,grade=game.profile.grade) {
 const p=gradeProgress(game,questions,grade);
 return '<div class="mastery-panel"><span>漢字 <b>'+p.mastered+' / '+p.total+'</b> 問せいかい</span><div class="mastery-meter" role="progressbar" aria-label="正解した問題数" aria-valuenow="'+p.mastered+'" aria-valuemax="'+p.total+'" aria-valuemin="0"><i style="width:'+100*p.mastered/p.total+'%"></i></div></div>';
}
export function homeScreen(game,questions,grades) {
 const practice=game.active?.round.mode==='practice';
 const base=game.active?monsterById(game.active.monsterId):encounter(game);
 const next=practice?{...base,grade:game.active.round.grade,area:game.active.round.grade-1}:base;
 // Review has its own opponent; the adventure route keeps its current stage.
 const route=practice?encounter(game):next,chapter=Math.floor(route.stage/5);
 const all=MONSTERS.filter(m=>m.grade===game.profile.grade), found=all.filter(m=>game.catches[m.id]).length;
 const count=game.active?game.active.targets.length-game.active.solved.length:battleTargets(game,questions,next).length;
 return `<section class="home-grade"><h1 tabindex="-1" data-focus>きょうは、何年生？</h1>${grades}</section><section class="quest-card"><div class="quest-copy"><p class="eyebrow">${practice?`復習バトル · ${game.active.targets.length}問`:`第${chapter+1}章 · ${next.stage+1} / 20`}</p><h2>${next.name}</h2><p class="quest-target">${game.active?.won?game.active.round.mode==='practice'?'れんしゅうクリア！':'クリア！ 竜が待っているよ。':`あと <b>${count}問</b> せいかいで${game.active?.round.mode==='practice'?'れんしゅうクリア':'仲間に'}`}</p><button class="primary" data-action="start">${game.active?.won?'結果を見る':game.active?'つづきから':'冒険に出発'} ${icon('arrow')}</button>${game.active?'<button class="text-button" data-action="stow">学年をえらび直す</button>':''}</div><div class="quest-scene ${next.kind}">${landscape(next.area)}<div class="quest-glow"></div>${monster(next)}${!practice&&next.kind!=='normal'?'<span class="boss-label">'+(next.kind==='final'?'天空の王':'ボス')+'</span>':''}</div></section><section class="home-progress"><button data-action="book">${icon('book')}図鑑 <b>${found}/20体</b></button>${progressPanel(game,questions)}</section><section class="current-chapter"><div class="section-head"><h2>第${chapter+1}章の道</h2><span>${['灼熱の試練','吹雪の試練','深淵の試練','天空への道'][chapter]}</span></div><div class="route-strip">${all.slice(chapter*5,chapter*5+5).map(m=>`<button class="route-node ${game.catches[m.id]?'found':''} ${m.id===route.id?'next':''}" data-monster="${m.id}"><span>${game.catches[m.id]?icon('check'):m.kind==='normal'?m.stage+1:icon('crown')}</span><small>${m.id===route.id?'つぎの相手':m.kind==='normal'?'ドラゴン':m.kind==='final'?'天空の王':'ボス'}</small></button>`).join('')}</div></section><section class="practice-launch"><div><h2>まちがいノート</h2><p>${weakQuestions(game,questions).length}問が復習を待っているよ。</p></div>${!game.active&&weakQuestions(game,questions).length?'<button class="secondary" data-action="practice">5問ずつ練習</button>':'<button class="secondary" data-action="history">ノートを見る</button>'}</section>`;
}
export function bookAreaScreen(game,questions,index) {
 const list=MONSTERS.filter(m=>m.area===index);
 return `<div class="section-head guide-heading"><h2>${index+1}年のドラゴン</h2><span>${list.filter(m=>game.catches[m.id]).length}/20体</span></div><div class="monster-grid">${list.map(m=>`<button class="specimen ${game.catches[m.id]?'discovered':'undiscovered'} ${m.kind}" data-monster="${m.id}"><span class="specimen-top"><small>${String(m.stage+1).padStart(2,'0')}</small><b>${m.kind==='normal'?'':m.kind==='boss'?'ボス':'天空の王'}</b></span>${monster(m,{silhouette:!game.catches[m.id]})}<h3>${game.catches[m.id]?m.name:'？？？'}</h3>${game.catches[m.id]?'<span class="dragon-stars">'+'★'.repeat(m.stars)+'</span>':'<p>'+requirement(game,questions,m)+'</p>'}</button>`).join('')}</div>`;
}
export function historyScreen(game, questions, grade, filter = 'all') {
  const all = mistakeHistory(game, questions, grade), list = filter === 'weak' ? all.filter(q => q.streak < 2) : all;
  return `<section class="book-shell history-shell"><div class="section-head"><div><h1 tabindex="-1" data-focus>まちがいノート</h1><p>まちがいの多い順に、練習しよう。</p></div><button class="quiet" data-action="home">${icon('back')}拠点へ</button></div><div class="book-tabs" role="group" aria-label="記録の学年">${AREAS.map((a, i) => `<button aria-pressed="${grade === i + 1}" data-history-grade="${i + 1}">${i + 1}年</button>`).join('')}</div><div class="history-summary"><b>${all.length} 問の記録</b><span>合計 ${all.reduce((s, q) => s + q.wrong, 0)} 回のまちがい</span><span>復習できた ${all.filter(q => q.streak >= 2).length} 問</span></div><div class="history-filters" role="group" aria-label="記録の絞りこみ"><button aria-pressed="${filter === 'all'}" data-history-filter="all">すべての記録</button><button aria-pressed="${filter === 'weak'}" data-history-filter="weak">復習したい問題</button></div><p class="muted">2回続けて正解で復習クリア。まちがいの回数は残ります。</p>${list.length ? `<div class="history-list">${list.map(q => `<article class="history-item"><div><h2><ruby>${esc(q.word)}<rt>${esc(q.reading)}</rt></ruby></h2><p>${esc(q.hint)}</p></div><div class="history-counts"><b>まちがい ${q.wrong} 回</b><span>正解 ${q.correct} 回 / 解答 ${q.seen} 回</span><span class="${q.streak >= 2 ? 'learned' : ''}">${q.streak >= 2 ? '✓ 復習できた' : '復習中'}</span></div></article>`).join('')}</div>` : '<div class="empty-note">この学年には、まだ該当する記録がないよ。<br>冒険でまちがえた問題が、ここにのこるよ。</div>'}${!game.active && all.some(q => q.streak < 2) ? `<button class="primary" data-review-grade="${grade}">5問ずつ練習 ${icon('arrow')}</button>` : ''}${game.legacy ? '<p class="muted legacy-note">旧バージョンの討伐記録も保存済み。学習履歴と最高コンボは新しい冒険に引き継いでいます。</p>' : ''}</section>`;
}
export function settingsScreen(game) {
 return `<h2 id="dialog-title">設定</h2><label class="setting"><span>効果音</span><input type="checkbox" id="sound-setting" ${game.profile.sound?'checked':''}></label><label class="setting audio-volume"><span>効果音の音量 <output data-volume="soundVolume">${Math.round((game.profile.soundVolume ?? .7)*100)}%</output></span><input type="range" id="sound-volume" min="0" max="100" step="5" value="${Math.round((game.profile.soundVolume ?? .7)*100)}"></label><label class="setting"><span>音楽（BGM）</span><input type="checkbox" id="music-setting" ${game.profile.music?'checked':''}></label><label class="setting audio-volume"><span>音楽の音量 <output data-volume="musicVolume">${Math.round((game.profile.musicVolume ?? .45)*100)}%</output></span><input type="range" id="music-volume" min="0" max="100" step="5" value="${Math.round((game.profile.musicVolume ?? .45)*100)}"></label><p class="audio-help">音楽は場面に合わせて変わるよ。休けい中はおやすみ。</p><label class="setting"><span>正解したら自動で次へ</span><input type="checkbox" id="auto-setting" ${game.profile.auto?'checked':''}></label><details class="help-details"><summary>あそび方</summary><ul><li>1問正解で10ダメージ。HPが0になれば勝利！</li><li>間違えてもHPは戻らないよ。</li><li>学年の全問に正解すると、天空の王が仲間に。</li></ul></details><button class="primary wide" data-action="close-dialog">もどる</button><details class="reset-section"><summary>データの管理</summary><p>全学年の記録と設定を初期化します。</p><button class="danger wide" data-action="reset-confirm">すべてのデータをクリア</button></details>`;
}
